services:
  app-blue:
    build: .
    container_name: training-app-blue
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db

  app-green:
    build: .
    container_name: training-app-green
    ports:
      - "8081:8080"
    volumes:
      - ./db:/app/db
    profiles:
      - green