version: '3.8'

services:
  app-blue:
    build: .
    container_name: training-app-blue
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/db

  app-green:
    build: .
    container_name: training-app-green
    ports:
      - "8081:8080"
    volumes:
      - db-data:/app/db
    profiles:
      - green

volumes:
  db-data:
